apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api

    spec:
      containers:
        - name: api
          image: mayurbrijwani/api-service:latest
          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"